package gui;

/**
 * Help Dialog
 */
public class Help extends javax.swing.JDialog {

  /** Creates new form Help */
  public Help(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  private void initComponents() {

    imagePanel = new javax.swing.JPanel();
    labelImageHelp = new javax.swing.JLabel();
    textPanel = new javax.swing.JPanel();
    textLabel1 = new javax.swing.JLabel();
    textLabel2 = new javax.swing.JLabel();
    backButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Ayuda de StickMotion");

    imagePanel.setBorder(javax.swing.BorderFactory
        .createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

    labelImageHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource(
        "/gui/images/helpImage.png")));

    javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(
        imagePanel);
    imagePanel.setLayout(imagePanelLayout);
    imagePanelLayout
        .setHorizontalGroup(imagePanelLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addComponent(
            labelImageHelp));
    imagePanelLayout
        .setVerticalGroup(imagePanelLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addComponent(
            labelImageHelp));

    textPanel.setBorder(javax.swing.BorderFactory
        .createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

    textLabel1.setText("Para la ayuda, consulte el manual que se adjunta");

    textLabel2.setText("en el CD proporcionado o en el manual impreso.");

    backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
        "/gui/images/next2.png")));
    backButton.setText("¡Volver!");
    backButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(
        textPanel);
    textPanel.setLayout(textPanelLayout);
    textPanelLayout.setHorizontalGroup(textPanelLayout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
        textPanelLayout.createSequentialGroup().addGroup(
            textPanelLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    textPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(
                            textPanelLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textLabel1).addComponent(
                                    textLabel2))).addGroup(
                    textPanelLayout.createSequentialGroup().addGap(131, 131,
                        131).addComponent(backButton))).addContainerGap(22,
            Short.MAX_VALUE)));
    textPanelLayout.setVerticalGroup(textPanelLayout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
        textPanelLayout.createSequentialGroup().addContainerGap().addComponent(
            textLabel1).addPreferredGap(
            javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
            textLabel2).addPreferredGap(
            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(
            backButton).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
            Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
        getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
        layout.createSequentialGroup().addContainerGap().addGroup(
            layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                textPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(
                imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(
            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    layout.setVerticalGroup(layout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
        layout.createSequentialGroup().addContainerGap().addComponent(
            imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE,
            javax.swing.GroupLayout.DEFAULT_SIZE,
            javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
            javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
            textPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
            javax.swing.GroupLayout.DEFAULT_SIZE,
            javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(
            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    pack();
  }

  /**
   * Method for hiding the panel when the "back" button is pressed
   * 
   * @param evt
   */
  private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // Cuando se pulse sobre el botón Volver
    setVisible(false);
  }

  /**
   * Main Methos
   * 
   * @param args
   *          the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        Help dialog = new Help(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  private javax.swing.JButton backButton;
  private javax.swing.JPanel imagePanel;
  private javax.swing.JLabel labelImageHelp;
  private javax.swing.JLabel textLabel1;
  private javax.swing.JLabel textLabel2;
  private javax.swing.JPanel textPanel;
}
